// Alexandros Apostolidis
public class FlussDaten {

    public static Fluss[] createFlussFeld() {
        Fluss[] fluesse = new Fluss[flussDaten.length];
        int i = 0;
        for (String[] row : flussDaten) {
            fluesse[i++] = new Fluss(toInt(row[0]),row[1],row[2],row[3],row[4]);
        }
        return fluesse;
    }

    /* wandelt einen String in ein int um (falls moeglich) */
    public static int toInt(String s) {
        return Integer.parseInt(s);
    }

    /* Feld von Feldern mit Strings, die jeweils einen Fluss beschreiben: 
       Laenge - Name - Kontinent - Quellgebiet - Muendung 
    */
    public static String[][] flussDaten = {
        {"6852","Nil mit Kagera-Nil","Afrika","Ruandaberge","Mittelmeer"},
        {"6448","Amazonas mit Ucayali, Tambo, Ene und Apurimac","Südamerika","Anden","Atlantischer Ozean"},
        {"6380","Jangtsekiang mit Tongtian He","Asien","Tibet","Ostchinesisches Meer"},
        {"6051","Mississippi mit Missouri, Jefferson und Red Rock River","Nordamerika","Rocky Mountains","Golf von Mexiko"},
        {"5540","Jenissei mit Angara, Selenga und Ider","Asien","Sajangebirge","Arktischer Ozean"},
        {"5410","Ob mit Irtysch","Asien","Mongolischer Altai","Obbusen"},
        {"5052","Amur mit Argun und Cherlen (episodisch)","Asien","Chentii-Gebirge","Ochotskisches Meer"},
        {"4845","Gelber Fluss","Asien","Tibet","Gelbes Meer"},
        {"4835","Kongo mit Luvua, Luapula und Chambeshi","Afrika","Südlich des Tanganjikasees","Atlantischer Ozean"},
        {"4500","Mekong","Asien","Tibet","Südchinesisches Meer"},
        {"4400","Lena","Asien","Baikalgebirge","Laptewsee"},
        {"4348","Ob mit Katun","Asien","Altai-Gebirge","Obbusen"},
        {"4260","Mackenzie mit Slave, Peace und Finlay","Nordamerika","Rocky Mountains","Beaufortsee"},
        {"4259","Jenissei mit Kleiner Jenissei und Schargyn gol","Asien","Sajangebirge","Arktischer Ozean"},
        {"4248","Irtysch","Asien","Mongolischer Altai","Ob"},
        {"4184","Niger","Afrika","Loma Mountains","Atlantischer Ozean"},
        {"4130","Missouri mit Jefferson und Red Rock River","Nordamerika","Rocky Mountains","Mississippi"},
        {"3998","Parana mit Rio Grande","Südamerika","Serra da Mantiqueira","Atlantischer Ozean, Rio de la Plata"},
        {"3778","Mississippi","Nordamerika","Lake Itasca","Golf von Mexiko"},
        {"3672","Murray River mit Darling River, Culgoa, Balonne und Condamine","Australien","Great Dividing Range","Indischer Ozean"},
        {"3596","Schatt al-Arab mit Euphrat und Murat","Asien","Nördlich des Vansee","Persischer Golf"},
        {"3530","Wolga","Europa","Waldaihöhen","Kaspisches Meer"},
        {"3500","Angara mit Selenga und Ider","Asien","Sajangebirge","Jenissei"},
        {"3450","Meghna mit Padma, Jamuna und Brahmaputra","Asien","Himalaya","Golf von Bengalen"},
        {"3380","Euphrat mit Murat","Asien","Nördlich des Vansee","Schatt al-Arab"},
        {"3380","Rio Madeira mit Rio Mamora und Rio Grande","Südamerika","Anden","Amazonas"},
        {"3283","Rio Jurua","Südamerika","Anden","Amazonas"},
        {"3210","Rio Purus","Südamerika","Anden","Amazonas"},
        {"3199","Rio Sao Francisco","Südamerika","Serra da Canastra","Atlantischer Ozean"},
        {"3185","Yukon mit Teslin und Nisutlin","Nordamerika","Rocky Mountains","Beringmeer"},
        {"3180","Indus","Asien","Himalaya","Arabisches Meer"},
        {"3100","Brahmaputra","Asien","Himalaya","Padma"},
        {"3034","Rio Grande","Nordamerika","Rocky Mountains","Golf von Mexiko"},
        {"3019","Syrdarja mit Naryn","Asien","Tian Shan","Aralsee"},
        {"3010","Orinoco mit Guaviare","Südamerika","Serra Parima","Atlantischer Ozean"},
        {"2989","Untere Tunguska","Asien","Mittelsibirisches Bergland","Jenissei"},
        {"2980","Saluen","Asien","Tibet","Andamanensee"},
        {"2857","Donau mit Breg","Europa","Schwarzwald","Schwarzes Meer"},
        {"2844","Darling River","Australien","Great Dividing Range","Murray"},
        {"2816","Rio Japura mit Rio Caqueta","Südamerika","Anden","Amazonas"},
        {"2743","Amudarja mit Pjandsch","Asien","Pamir/Hindukusch","Aralsee"},
        {"2671","Nelson River mit Saskatchewan, South Saskatchewan und Bow","Nordamerika","Rocky Mountains","Hudson Bay"},
        {"2650","Wiljui","Asien","Mittelsibirisches Bergland","Lena"},
        {"2574","Sambesi","Afrika","Lundaschwelle","Indischer Ozean"},
        {"2549","Rio Paraguay","Südamerika","Mato-Grosso-Plateau","Rio Parana"},
        {"2513","Kolyma","Asien","Kolymagebirge","Ostsibirische See"},
        {"2511","Ganges","Asien","Himalaya","Padma"},
        {"2508","Murray River","Australien","Great Dividing Range","Indischer Ozean"},
        {"2450","Rio Tocantins mit Rio Araguaia","Südamerika","Serra dos Caiapos","Atlantischer Ozean"},
        {"2450","Ischim","Asien","Kasachische Schwelle","Irtysch"},
        {"2428","Ural","Europa/Asien","Uralgebirge","Kaspisches Meer"},
        {"2421","Sankt-Lorenz-Strom mit North River","Nordamerika","Minnesota","Atlantischer Ozean"},
        {"2400","Rio Negro mit Rio Vaupes","Südamerika","Anden","Amazonas"},
        {"2338","Slave mit Peace und Finlay","Nordamerika","Rocky Mountains","Großer Sklavensee, Mackenzie"},
        {"2333","Colorado River","Nordamerika","Rocky Mountains","Pazifischer Ozean"},
        {"2333","Arkansas","Nordamerika","Rocky Mountains","Mississippi"},
        {"2292","Olenjok","Asien","Mittelsibirisches Bergland","Arktischer Ozean/Laptewsee"},
        {"2291","Rio Tapajos mit Teles Pires","Südamerika","Mato-Grosso-Plateau","Amazonas"},
        {"2285","Dnepr","Europa","Waldaihöhen","Schwarzes Meer"},
        {"2273","Aldan","Asien","Stanowoigebirge","Lena"},
        {"2272","Ubangi mit Uelle","Afrika","Zentralafrikanische Schwelle","Kongo"},
        {"2240","Columbia River mit Snake River","Nordamerika","Rocky Mountains","Pazifischer Ozean"},
        {"2198","Rio Araguaia","Südamerika","Serra dos Caiapos","Rio Tocantins"},
        {"2197","Westfluss (Xi Jiang)","Asien","Llanwan Shan","Südchinesisches Meer"},
        {"2190","Tarim mit Yarkant","Asien","Karakorum","Lop Nor"},
        {"2188","Red River mit Tierra Blanca Creek und Frio Creek (episodisch)","Nordamerika","Rocky Mountains","Mississippi"},
        {"2170","Irrawaddy","Asien","Himalaya","Andamanensee"},
        {"2160","Oranje","Afrika","Hochland von Lesotho","Atlantischer Ozean"},
        {"2153","Kasai","Afrika","Hochland von Bie","Kongo"},
        {"2140","Orinoco","Südamerika","Serra Parima","Atlantischer Ozean"},
        {"2102","Ohio River mit Allegheny","Nordamerika","Appalachen","Mississippi"},
        {"2060","Brazos River","Nordamerika","New Mexiko, Grenze zu Texas","Golf von Mexiko"},
        {"2023","Tschulym mit Weißer Ijus","Asien","Kusnezker Alatau","Ob"},
        {"2011","Rio Salado del Norte","Südamerika","Anden","Rio Parana"},
        {"1999","Rio Pilcomayo","Süamerika","Anden","Rio Paraguay"},
        {"1980","Rio Xingu","Südamerika","Mato-Grosso-Plateau","Amazonas"},
        {"1978","Witim","Asien","Ikatberge","Lena"},
        {"1977","Indigirka mit Chastach","Asien","Werchojansker Gebirge","Ostsibirische See"},
        {"1905","Maranon","Südamerika","Anden","Quellfluss des Amazonas"},
        {"1899","Tigris","Asien","Ost-Taurusgebirge","Schatt al-Arab"},
        {"1872","Rio Colorado mit Rio Salado del Oeste","Südamerika","Anden","Atlantischer Ozean"},
        {"1870","Don","Europa","Mittelrussische Platte","Schwarzes Meer"},
        {"1840","Songhua","Asien","Changbai-Gebirge","Amur"},
        {"1830","Steinige Tunguska","Asien","Mittelsibirisches Bergland","Jenissei"},
        {"1820","Shabelle","Afrika","Mendebo-Gebirge","Juba"},
        {"1819","Volta mit Schwarzem Volta","Afrika","Bobo-Dioulasso","Atlantischer Ozean"},
        {"1813","Rio Putumayo","Südamerika","Anden","Amazonas"},
        {"1809","Petschora","Europa","Ural","Barentssee"},
        {"1806","Nördliche Dwina mit Wytschegda","Europa","Timanrücken","Weißes Meer"},
        {"1805","Kama","Europa","Kamahöhen","Wolga"},
        {"1800","Okavango","Afrika","Hochland von Bie","versiegt im Okavangobecken"},
        {"1790","Rio Uruguay","Südamerika","Südbrasilianisches Bergland","Atlantischer Ozean, Rio de la Plata"},
        {"1783","Blauer Nil","Afrika","Hochland von Abessinien","Nil"},
        {"1779","Angara","Asien","Baikalsee","Jenissei"},
        {"1750","Limpopo","Afrika","Witwatersrand","Indischer Ozean"},
        {"1740","Schari mit Ouham","Afrika","Nordäquatorialschwelle","Tschadsee"},
        {"1716","Rio Parnaiba","Südamerika","Brasilianisches Bergland","Atlantischer Ozean"},
        {"1670","Snake River","Nordamerika","Rocky Mountains","Columbia River"},
        {"1663","Alaseja mit Kadyltschan","Asien","Alaseja-Plateau","Ostsibirische See"},
        {"1658","Juba","Afrika","Äthiopisches Bergland","Indischer Ozean"},
        {"1636","Chatanga mit Kotui","Asien","Putorana-Gebirge","Chatangabusen, Laptewsee"},
        {"1621","Ket","Asien","Region Krasnojarsk","Ob"},
        {"1620","Argun","Asien","Großes Hinggan-Gebirge","Quellfluss des Amur"},
        {"1611","Javari","Südamerika","Anden","Amazonas"},
        {"1609","Churchill River","Nordamerika","Alberta","Hudson Bay"},
        {"1593","Platte River mit North Platte River","Nordamerika","Rocky Mountains","Missouri"},
        {"1592","Schilka mit Onon","Asien","Jablonowygebirge","Quellfluss des Amur"},
        {"1591","Tobol","Asien","Ural","Irtysch"},
        {"1579","Murrumbidgee River","Australien","Snowy Mountains","Murray"},
        {"1559","Rio Beni","Südamerika","Anden","Quellfluss des Rio Madeira"},
        {"1551","Satluj mit Panjnad","Asien","Tibet","Indus"},
        {"1538","Rio Magdalena","Südamerika","Zentralkordillere","Karibisches Meer"},
        {"1532","Han Jiang","Asien","Provinz Shaanxi","Jangtsekiang"},
        {"1500","Cuando","Afrika","Hochland von Bie","Sambesi"},
        {"1497","Rio Guaviare","Südamerika","Ostkordillere","Orinoco"},
        {"1492","Jana mit Sartang","Asien","Werchojansker Gebirge","Laptewsee"},
        {"1490","Pecos River","Nordamerika","Rocky Mountains","Rio Grande"},
        {"1488","Jutai","Südamerika","Amazonastiefland","Amazonas"},
        {"1486","Kotui","Asien","Putoranagebirge","Quellfluss des Chatanga"},
        {"1484","Lachlan River","Australien","Snowy Mountains","Murrumbidgee"},
        {"1480","Napo","Südamerika","Anden","Amazonas"},
        {"1480","Oka","Europa","Mittelrussische Platte","Wolga"},
        {"1480","Selenga mit Ider","Asien","Changai-Gebirge","Baikalsee"},
        {"1465","Godavari","Asien","Hochland des Dekkan","Golf von Bengalen"},
        {"1462","Amga","Asien","Aldanhochland","Aldan"},
        {"1458","Canadian River","Nordamerika","Rocky Mountains","Arkansas"},
        {"1450","Rio Bermejo","Südamerika","Anden","Rio Paraguay"},
        {"1450","Lomami","Afrika","Nördlich der Lundaschwelle","Kongo"},
        {"1439","Ili mit Tekes","Asien","Tian Shan","Balchasch-See"},
        {"1438","Colorado River (Texas)","Nordamerika","Rocky Mountains","Golf von Mexiko"},
        {"1436","Oljokma","Asien","Jablonowygebirge","Lena"},
        {"1430","Rio Branco","Südamerika","Serra Parima","Rio Negro"},
        {"1430","Belaja","Europa","Ural","Kama"},
        {"1430","Senegal mit Bafing","Afrika","Bergland von Fouta Djallon","Atlantischer Ozean"},
        {"1425","Tennessee mit French Broad River","Nordamerika","Blue Ridge Mountains","Ohio"},
        {"1420","Cooper Creek (periodisch)","Australien","Great Dividing Range","Eyresee"},
        {"1416","Benue","Afrika","Hochland von Adamaua","Niger"},
        {"1401","Tas","Asien","Westsibirisches Tiefland","Tasbusen, Karasee"},
        {"1400","Luvua mit Luapula und Chambeshi","Afrika","Südlich des Tanganjikasees","Kongo"},
        {"1392","South Saskatchewan River","Nordamerika","Rocky Mountains","Quellfluss des Saskatchewan"},
        {"1391","Tawda mit Soswa","Asien","Ural","Tobol"},
        {"1376","Yamuna","Asien","Himalaya","Ganges"},
        {"1375","Rio Vaupes","Südamerika","Andenvorland","Rio Negro"},
        {"1370","Teles Pires","Südamerika","Mato-Grosso-Plateau","Quellfluss des Rio Tapajos"},
        {"1368","Fraser River","Nordamerika","Rocky Mountains","Pazifischer Ozean"},
        {"1364","Kura","Asien","Gebiet Kars","Kaspisches Meer"},
        {"1364","Rio Guapore","Südamerika","Mato-Grosso-Plateau","Rio Madeira"},
        {"1362","Pjassina mit Dudypta","Asien","Nordsibirisches Tiefland","Karasee"},
        {"1355","Kizilirmak","Asien","Ostanatolisches Hochland","Schwarzes Meer"},
        {"1352","Dnister","Europa","Waldkarpaten","Schwarzes Meer"},
        {"1349","Rio Cauca","Südamerika","Hochebenen von Sotara","Rio Magdalena"},
        {"1345","Liao","Asien","Mandschurisches Tiefland","Gelbes Meer"},
        {"1323","Yalong","Asien","Bayan Har Shan","Jangtsekiang"},
        {"1320","Iguacu","Südamerika","Serra da Mantiqueira","Rio Parana"},
        {"1319","Tassejewa mit Tschuna","Asien","Sajangebirge","Angara"},
        {"1314","Wjatka","Europa","Ural","Kama"},
        {"1310","Narmada","Asien","Hochland des Dekkan","Arabisches Meer"},
        {"1310","Rio Tahuamanu mit Rio Orthon","Südamerika","Voranden von Peru","Rio Beni"},
        {"1300","Rio Negro mit Rio Neuquen","Südamerika","Anden","Atlantischer Ozean"},
        {"1291","Krishna","Asien","Hochland des Dekkan","Golf von Bengalen"},
        {"1290","North Canadian River","Nordamerika","Rocky Mountains","Canadian River"},
        {"1288","Shire mit Ruhuhu","Afrika","Livingstone-Berge","Sambesi"},
        {"1287","Aruwimi","Afrika","Blaues Gebirge","Kongo"},
        {"1287","North Saskatchewan River","Nordamerika","Rocky Mountains","Saskatchewan"},
        {"1271","Ottawa River","Nordamerika","Abfluss des Capimitchigama-See","Sankt-Lorenz-Strom"},
        {"1254","Cherlen","Asien","Chentii-Gebirge","Hulun Nur"},
        {"1251","Vaal","Afrika","Drakensberge","Oranje"},
        {"1245","Elbe mit Moldau","Europa","Riesengebirge, Böhmerwald","Nordsee"},
        {"1242","Chenab","Asien","Himalaya","Panjnad"},
        {"1242","Seja","Asien","Stanowoigebirge","Amur"},
        {"1240","Rio Juruena","Südamerika","Mato-Grosso-Plateau","Quellfluss des Rio Tapajos"},
        {"1233","Rhein","Europa","Schweizer Alpen","Nordsee"},
        {"1231","Athabasca River","Nordamerika","Rocky Mountains","Quellfluss des Mackenzie"},
        {"1215","Liard River","Nordamerika","Rocky Mountains","Mackenzie"},
        {"1200","Rio Aripuana","Südamerika","Mato-Grosso-Plateau","Rio Madeira"},
        {"1200","Rio Meta","Südamerika","Ostkordillere","Orinoco"},
        {"1200","Red River of the North mit Sheyenne River","Nordamerika","Missouriplateau","Winnipegsee"},
        {"1190","Rio Acre","Südamerika","Anden","Rio Purus"},
        {"1181","Marcha","Asien","Mittelsibirisches Bergland","Wiljui"},
        {"1175","Green River","Nordamerika","Rocky Mountains","Colorado River"},
        {"1175","Mamberamo mit Taritatu und Sobger","Australien","Pegunungan Maoke","Pazifischer Ozean"},
        {"1174","Kansas River mit Smoky Hill River","Nordamerika","Rocky Mountains","Missouri"},
        {"1173","Milk River","Nordamerika","Rocky Mountains","Missouri"},
        {"1170","Nen Jiang","Asien","Großes Hinggan-Gebirge","Songhua Jiang"},
        {"1165","Kuskokwim River","Nordamerika","Alaskakette","Beringmeer"},
        {"1161","White River","Nordamerika","Ozark-Plateau","Mississippi"},
        {"1160","Comoe","Afrika","Bobo-Dioulasso","Atlantischer Ozean"},
        {"1160","Orchon mit Tuul","Asien","Chentii-Gebirge","Selenga"},
        {"1160","Demjanka","Asien","Wassjuganje","Irtysch"},
        {"1150","Rio Madre de Dios","Südamerika","Anden","Rio Beni"},
        {"1150","Omolon","Asien","Kolymagebirge","Kolyma"},
        {"1150","Sankuru","Afrika","Lundaschwelle","Kasai"},
        {"1150","Xiang Jiang","Asien","Südostchinesisches Hügelland","Jangtsekiang"},
        {"1149","Roter Fluss","Asien","Provinz Yünnan","Südchinesisches Meer"},
        {"1146","Anadyr","Asien","Anjuigebirge","Beringmeer"},
        {"1143","James River","Nordamerika","Wells County","Missouri"},
        {"1143","Kapuas","Asien","Kapuasgebirge","Südchinesisches Meer"},
        {"1140","Weißer Volta (Oberlauf periodisch)","Afrika","Oberguineaschwelle","Volta"},
        {"1138","Rio Huallaga","Südamerika","Anden","Maranon"},
        {"1130","Desna","Europa","Smolensker Höhen","Dnepr"},
        {"1130","Hilmend","Asien","Hindukusch","Hilmendsee"},
        {"1130","Rio Tiete","Südamerika","Serra da Mantiqueira","Rio Parana"},
        {"1130","Georgina River (periodisch)","Australien","Barkly Tableland","Lake Eyre"},
        {"1126","Sepik","Australien","Neuguinea, Victor Emanuel Range","Bismarcksee"},
        {"1126","Wu Jiang mit Yachi He und Sancha He","Asien","Wumeng Shan","Jangtsekiang"},
        {"1125","Rio Iriri","Südamerika","Mato-Grosso-Plateau","Rio Xingu"},
        {"1124","Hari Rud","Asien","Koh-e Baba-Gebirge","versiegt, Wüste Karakum"},
        {"1124","Wach","Asien","Westsibirisches Tiefland","Ob"},
        {"1123","Cimarron River","Nordamerika","Rocky Mountains","Arkansas"},
        {"1120","Atbara","Afrika","Hochland von Abessinien","Nil"},
        {"1120","Fly","Australien","Maokegebirge","Korallenmeer"},
        {"1120","Gambia","Afrika","Bergland von Fouta Djallon","Atlantischer Ozean"},
        {"1119","Jialing","Asien","Provinz Shaanxi","Jangtsekiang"},
        {"1112","Chao Phraya mit Nan","Asien","Provinz Nan, Thailand","Golf von Thailand"},
        {"1106","Cumberland River","Nordamerika","Appalachen","Ohio"},
        {"1100","Kwango","Afrika","Lundaschwelle","Kasai"},
        {"1100","Sangha mit Mambere","Afrika","Hochland von Adamaua","Kongo"},
        {"1100","Wadi Draa (periodisch)","Afrika","Atlas","Atlantischer Ozean"},
        {"1097","Konda","Asien","Westsibirisches Tiefland","Irtysch"},
        {"1095","Rio Apure mit Rio Uribante","Südamerika","Ostkordillere","Orinoco"},
        {"1094","Ogooue","Afrika","Niederguineaschwelle","Atlantischer Ozean"},
        {"1092","Tjung","Asien","Mittelsibirisches Bergland","Wiljui"},
        {"1091","Om","Asien","Westsibirisches Tiefland","Irtysch"},
        {"1083","Rovuma","Afrika","Östlich des Malawisees","Indischer Ozean"},
        {"1082","Jequitinhonha","Südamerika","Minas Gerais","Atlantischer Ozean"},
        {"1082","Wassjugan","Asien","Westsibirisches Tiefland","Ob"},
        {"1080","Yellowstone River","Nordamerika","Rocky Mountains","Missouri"},
        {"1078","Huai He","Asien","Tongbai-Gebirge","Ostchinesisches Meer"},
        {"1072","Aras","Asien","Bingöl-Gebirge","Kura"},
        {"1070","Assiniboine River","Nordamerika","Saskatchewan","Red River of the North"},
        {"1070","Rio Paranaiba","Südamerika","Serra da Mata da Cordoba","Quellfluss des Rio Parana"},
        {"1067","Tschui","Asien","Kirgisisches Gebirge","Depression Asikol"},
        {"1063","Großer Jugan","Asien","Wassjuganje","Ob"},
        {"1062","Trinity River mit Trinity River West Fork","Nordamerika","Texas, nordwestlich Dallas","Golf von Mexiko, Galveston Bay"},
        {"1060","Lukeni mit Fimi","Afrika","Östlich von Lodja","Kasai"},
        {"1060","Sanaga mit Djerem","Afrika","Hochland von Adamaua","Atlantischer Ozean"},
        {"1060","Tanana River","Nordamerika","Alaskakette","Yukon"},
        {"1058","Chindwin","Asien","Patkai-Gebirge","Irrawaddy"},
        {"1053","Donez","Europa","Mittelrussische Platte","Don"},
        {"1053","Maja","Asien","Dschugdschur","Aldan"},
        {"1050","Arauca","Südamerika","Ostkordillere","Orinoco"},
        {"1050","Bani mit Baoule","Afrika","Bergland der Elfenbeinküste","Niger"},
        {"1050","Chambal","Asien","Vindhyagebirge","Yamuna"},
        {"1050","Rio Paraiba","Südamerika","Serra da Mantiqueira","Atlantischer Ozean"},
        {"1047","Weichsel","Europa","Westbeskiden","Ostsee"},
        {"1045","Oder mit Warthe","Europa","Krakau-Tschenstochauer Jura","Ostsee"},
        {"1040","Mobile River mit Alabama River und Coosa River","Nordamerika","Appalachen","Golf von Mexiko"},
        {"1040","Chattahoochee River","Nordamerika","Appalachen","Golf von Mexiko"},
        {"1035","Hotan","Asien","Karakorum","Tarim"},
        {"1033","Yuan Jiang","Asien","Guizhou","Jangtsekiang"},
        {"1030","Ghagara","Asien","Himalaya","Ganges"},
        {"1030","Tura","Asien","Ural","Tobol"},
        {"1025","Ruki mit Busira und Tshuapa","Afrika","Kongobecken","Kongo"},
        {"1024","Pur mit Pjakupur und Jangjagun","Asien","Westsibirisches Tiefland","Tasbusen, Karasee"},
        {"1020","Duna","Europa","Waldaihöhen","Ostsee"},
        {"1020","Kunene","Afrika","Hochland von Bie","Atlantischer Ozean"},
        {"1020","Loire","Europa","Zentralmassiv","Atlantischer Ozean"},
        {"1016","Newa mit Wolchow, Msta und Zna","Europa","Waldaihöhen","Ostsee"},
        {"1014","Gila River","Nordamerika","Rocky Mountains","Colorado River"},
        {"1012","Birjussa","Asien","Sajangebirge","Tassejewa"},
        {"1010","Chopjor","Europa","Wolgaplatte","Don"},
        {"1010","Essequibo","Südamerika","Acarai Mountains","Atlantischer Ozean"},
        {"1007","Tajo","Europa","Sierra de Albarracin","Atlantischer Ozean"},
        {"1004","Flinders River","Australien","Great Dividing Range","Golf von Carpentaria"},
        {"1000","Rio Grande de Santiago mit Lerma","Nordamerika","Hochland von Mexiko","Pazifischer Ozean"},
        {"1000","Kwilu","Afrika","Hochland von Bie","Kwango"}};
}
